spring:
  application:
    name: user-service

#MongoDB Atlas
  data:
    mongodb:
      uri: mongodb+srv://grazielleanaia_db_user:8tcuRSNAofMUgI3s@users-data.nvfnkmx.mongodb.net/userdb
      database: userdb

server:
  port: 8082