spring:
  application:
    name: user-service

  #PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: graziuser
    password: grazipassword
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082