spring:
  application:
    name: product-service
  #PostgreSQL
  datasource:
#    url: jdbc:postgresql://localhost:5432/product
    url: jdbc:postgresql://ep-flat-thunder-ae2aoof5-pooler.c-2.us-east-2.aws.neon.tech/product?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_Zs8OcvBkeY9U
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
