spring:
  application:
    name: notification
  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:guest}
    connection-timeout: 30000

rabbitmq:
  exchange:
    name: exchange.order
  queue:
    name: queue.order
  routing:
    key: tracking.order

server:
  port: 8084